theme: hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: QA Diva: Adventures in Coding
description: Come along, friends, and see what trouble I can get into
