
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 

title: Journeys of a Quality Architect

description: Come along, friends, and see what trouble I can get into


[So I've decided to try github pages...][./2023-01-17-newBlog.html]